version: 0.2

env:
    variables:
        APP_NAME: ""
        BUILD_ENV : ""

phases:
    install:
        commands:
        
        # Download and Install NodeJS 8.0     
        - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
        - sudo apt-get install -y nodejs
        - echo Installing source NPM dependencies...
        # Install http drivers for node
        - echo Installing serverless...
        - npm install -g serverless
        - npm install


    build:
        commands:
        # Builds serverles application.
        - echo Build started on `date`
        - serverless deploy --stage ${BUILD_ENV} | tee deploy.out

    post_build:
        commands:
        - echo Build completed on `date`

artifacts:
    files:
        – serverless.yml
    discard-paths: yes