region: us-east-1
stage: dev
role: arn:aws:iam::026430579524:role/lambda-tgr-pit
bucket: tgr-dev-contribuciones-tokens-pit
api: #Diferencia
  grantType: client_credentials
  clientSecret: TGR.C0ntr!bUC10n3s
  clientId: OauthTrContribucionesRsClient
  scope: /ClienteBienRaizWS/api/BienRaiz* /RecuperaDeudaROLRS/api/bienraiz/* /BienRaizWS/api/BienRaiz* /tgrSuscriptorWs/api/suscriptor* /recaPagoConsultasWS/api/pago/consulta
  hostname: wstest.tesoreria.cl
  port: 443
accessControlAllowOrigin: "*"
cognito: arn:aws:cognito-idp:us-east-1:080540609156:userpool/us-east-1_dD7fg7AJB
apiId: 9l70yekz53
apiRootId: p384k1g8s8
apiHostnameVerifyCaptcha: www.google.com
apipathVerifyCaptcha: /recaptcha/api/siteverify
idAppRecaptcha2: 6LcObZUUAAAAAJ371RFuzWx-Q9ebINm5VVUlAb5Y
idAppRecaptcha3: 6Lc2dpUUAAAAACdFyhwIBgpNo8Y735oQWIBNU0Vj
threshold: 0.1
cors: true
elasticsearch:
  endpoint: search-dev-contribuciones-qj3q3jeqbkw5ix5ybdrdlpfqq4.us-east-1.es.amazonaws.com
  maxSize: 60
  maxSizeAutoComplate: 10

