region: us-east-1
stage: dev
role: arn:aws:iam::080540609156:role/tgr-dev-contribuciones-back-lambda
bucket: tgr-dev-contribuciones-tokens-pit
bucketParse: tgr-dev-contribuciones-parse-pit
keyParse: parse.json
api: #awsTierra #Diferencia
  grantType: client_credentials
  hostname: wstest.tesoreria.cl
  port: 443
  contribucion: #Diferencia
    clientSecret: TGR.C0ntr!bUC10n3s
    clientId: OauthTrContribucionesRsClient
    scope: /LiquidacionDeudaRs/api/bienraiz/* /PagoTotalRS/api/bienraiz* /tgrClientesWsCorreo/api/correosws* /tgrClientesWsCuentas/api/cuentaws/* /tgrClientesWsDatosBasicos/api/datosbasicosws* /tgrClientesWsDireccion/api/direccionws/* /tgrClientesWsTelefono/api/telefonows* /RecuperaDeudaROLRS/api/bienraiz/* /ClienteBienRaizWS/api/BienRaiz* /BienRaizWS/api/BienRaiz*
  cuenta: #Diferencia
    clientSecret: TGR.Cu2t!
    clientId: OauthTrCuentaTgrRsClient
    scope: /tgrSuscriptorWs/api/suscriptor* /recaPagoConsultasWS/api/pago/consulta /tgrTablasGralesWs/api/tablasgrales/*
accessControlAllowOrigin: "*"
cognito: arn:aws:cognito-idp:us-east-1:080540609156:userpool/us-east-1_dD7fg7AJB
apiId: 9l70yekz53
apiRootId: p384k1g8s8
apiHostnameVerifyCaptcha: www.google.com
apipathVerifyCaptcha: /recaptcha/api/siteverify
idAppRecaptcha2: 6LcObZUUAAAAAJ371RFuzWx-Q9ebINm5VVUlAb5Y
idAppRecaptcha3: 6Lc2dpUUAAAAACdFyhwIBgpNo8Y735oQWIBNU0Vj
threshold: 0.5
