region: us-east-1
stage: BUILD_ENV
role: BUILD_LAMBDA_ROLE_ARN
bucket: BUILD_BUCKET_TOKENS
bucketParse: BUILD_BUCKET_PARSE
keyParse: parse.json
api: #Diferencia
  grantType: BUILD_WST_GRANT_TYPE
  hostname: BUILD_WST_HOST
  port: BUILD_WST_PORT
  contribucion: #Diferencia
    clientSecret: TGR.C0ntr!bUC10n3s #Diferencia
    clientId: OauthTrContribucionesRsClient #Diferencia
    scope: /LiquidacionDeudaRs/api/bienraiz/* /PagoTotalRS/api/bienraiz* /tgrClientesWsCorreo/api/correosws* /tgrClientesWsCuentas/api/cuentaws/* /tgrClientesWsDatosBasicos/api/datosbasicosws* /tgrClientesWsDireccion/api/direccionws/* /tgrClientesWsTelefono/api/telefonows* /RecuperaDeudaROLRS/api/bienraiz/* /ClienteBienRaizWS/api/BienRaiz* /BienRaizWS/api/BienRaiz* #Diferencia
  cuenta: #Diferencia
    clientSecret: TGR.Cu2t! #Diferencia
    clientId: OauthTrCuentaTgrRsClient #Diferencia
    scope: /tgrSuscriptorWs/api/suscriptor* /recaPagoConsultasWS/api/pago/consulta /tgrTablasGralesWs/api/tablasgrales/* #Diferencia
accessControlAllowOrigin: "*"
cognito: BUILD_COGNITO_POOL_ARN
apiId: BUILD_API_ID
apiRootId: BUILD_API_ROOT_ID
apiHostnameVerifyCaptcha: www.google.com #Diferencia
apipathVerifyCaptcha: /recaptcha/api/siteverify #Diferencia
idAppRecaptcha2: 6LcObZUUAAAAAJ371RFuzWx-Q9ebINm5VVUlAb5Y #Diferencia
idAppRecaptcha3: 6Lc2dpUUAAAAACdFyhwIBgpNo8Y735oQWIBNU0Vj #Diferencia
threshold: 0.5 #Diferencia

