service: tgr-contribuciones-back

custom: ${file(./config.yml)}

provider:
  name: aws
  runtime: nodejs8.10
  region: ${self:custom.region}
  stage: ${self:custom.stage}
  role: ${self:custom.role}
  apiGateway:
    restApiId: ${self:custom.apiId}
    restApiRootResourceId: ${self:custom.apiRootId}

package:
  exclude:
  - test/*
  - package-lock.json
  - package.json
  - tgr-parse-proxies-poc-dev/*

functions:

  proxyPrivate:
    handler: proxy-private.handler
    timeout: 30
    events:
    - http:
        path: proxy-private
        method: post
        cors: true
        authorizer:
          arn: ${self:custom.cognito}
    - http:
        path: proxy-private
        method: get
        cors: true
        authorizer:
          arn: ${self:custom.cognito}
    environment:
      wsHostname: ${self:custom.wsTierra.hostname}
      wsPort: ${self:custom.wsTierra.port}
      bucket: ${self:custom.bucket}
      bucketParse: ${self:custom.bucketParse}
      keyParse: parse.json
      accessControlAllowOrigin: ${self:custom.accessControlAllowOrigin}

  proxyPublic:
    handler: proxy-public.handler
    timeout: 30
    events:
    - http:
        path: proxy-public
        method: post
        cors: true
    - http:
        path: proxy-public
        method: get
        cors: true

    environment:
      wsHostname: ${self:custom.wsTierra.hostname}
      wsPort: ${self:custom.wsTierra.port}
      bucket: ${self:custom.bucket}
      bucketParse: ${self:custom.bucketParse}
      keyParse: ${self:custom.keyParse}
      accessControlAllowOrigin: ${self:custom.accessControlAllowOrigin}

  tokensRenew:
    handler: tokens-renew.handler

    events:
    - schedule: rate(4 minutes)

    environment:
      foo: bar
      wsHostname: ${self:custom.wsTierra.hostname}
      wsPort: ${self:custom.wsTierra.port}
      tokenGrantType: ${self:custom.wsTierra.grantType}
      tokenClienteSecret: ${self:custom.wsTierra.clienteSecret}
      tokenClienteId: ${self:custom.wsTierra.clienteId}
      tokenScope: ${self:custom.wsTierra.scope}
      bucket: ${self:custom.bucket}
